languageCode = "zh_CN"
title = "My Blog"
baseURL = "http://www.pugongyingbo.com/"
theme = "material-design"
paginate = 9 
copyright = "© 2017 Copyright Text"

[params]
	description = "pugongyingbo@163.com"
	github = "https://github.com/pugongyingbo"
	weibo = "http://weibo.com/pugongyingbo"


[permalinks]
  post = "/:year/:month/:day/:title/"